[package]
name = "pub_fields"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn           = { version = "2.0", features = ["full"] }
quote         = "1"
proc-macro2   = "1"

[dev-dependencies]
trybuild = "1"
