apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: atomix
spec:
  containers:
  - name: debug-container
    image: cassandra:5.0
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    volumeMounts:
    - name: config
      mountPath: /etc/atomix
  volumes:
  - name: config
    configMap:
      name: atomix-rangeserver-config
  restartPolicy: Never
