apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-epoch
  namespace: atomix
spec:
  serviceName: "atomix-epoch"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-epoch
  template:
    metadata:
      labels:
        app: atomix-epoch
    spec:
      containers:
      - name: epoch
        image: atomix-epoch:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50050
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && epoch"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config

---
apiVersion: v1
kind: Service
metadata:
  name: atomix-epoch
  namespace: atomix
spec:
  selector:
    app: atomix-epoch
  # TODO: Expose epoch service ports
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50050
      targetPort: 50050