---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-universe
  namespace: atomix
  labels:
    app: atomix-universe
spec:
  serviceName: atomix-universe
  replicas: 1
  selector:
    matchLabels:
      app: atomix-universe
  template:
    metadata:
      labels:
        app: atomix-universe
    spec:
      containers:
      - name: universe
        image: atomix-universe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50056
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && universe --config /etc/atomix/config.json"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-universe-config
---
apiVersion: v1
kind: Service
metadata:
  name: atomix-universe
  namespace: atomix
  labels:
    app: atomix-universe
spec:
  ports:
  - port: 50056
    name: grpc
  clusterIP: None
  selector:
    app: atomix-universe

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atomix-universe-config
  namespace: atomix
data:
  config.json: |
    {
      "range_server": {
          "range_maintenance_duration": {
              "secs": 1,
              "nanos": 0
          },
          "proto_server_addr": "0.0.0.0:50054",
          "fast_network_addr": "0.0.0.0:50055"
        },
        "universe": {
            "proto_server_addr": "0.0.0.0:50056"
        },
        "frontend": {
            "proto_server_addr": "0.0.0.0:50057",
            "fast_network_addr": "0.0.0.0:50058",
            "transaction_overall_timeout": {
                "secs": 10,
                "nanos": 0
            }
        },
        "epoch": {
            "proto_server_addr": "atomix-epoch:50050",
            "epoch_duration": {
                "secs": 0,
                "nanos": 1000000000
            }
        },
        "cassandra": {
            "cql_addr": "cassandra:9042"
        },
        "regions": {
            "test-region": {
                "warden_address": "atomix-warden:50053",
                "epoch_publishers": [
                    {
                        "name": "ps1",
                        "zone": "test-region/a",
                        "publishers": [
                            {
                                "name": "ep1",
                                "backend_addr": "atomix-epoch-publisher:50051",
                                "fast_network_addr": "atomix-epoch-publisher:50052"
                            }
                        ]
                    }
                ]
            }
        }
    }