---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-universe
  namespace: atomix
  labels:
    app: atomix-universe
spec:
  serviceName: atomix-universe
  replicas: 1
  selector:
    matchLabels:
      app: atomix-universe
  template:
    metadata:
      labels:
        app: atomix-universe
    spec:
      containers:
      - name: universe
        image: atomix-universe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50056
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && universe --config /etc/atomix/config.json"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config
---
apiVersion: v1
kind: Service
metadata:
  name: atomix-universe
  namespace: atomix
  labels:
    app: atomix-universe
spec:
  ports:
  - port: 50056
    name: grpc
  clusterIP: None
  selector:
    app: atomix-universe