apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-warden
  namespace: atomix
spec:
  serviceName: "atomix-warden"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-warden
  template:
    metadata:
      labels:
        app: atomix-warden
    spec:
      containers:
      - name: warden
        image: atomix-warden:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: RUST_BACKTRACE
            value: "1"
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 50053
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && warden"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config

---
apiVersion: v1
kind: Service
metadata:
  name: atomix-warden
  namespace: atomix
spec:
  selector:
    app: atomix-warden
  # TODO: Expose warden ports
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053