apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-warden
  namespace: atomix
spec:
  serviceName: "atomix-warden"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-warden
  template:
    metadata:
      labels:
        app: atomix-warden
    spec:
      containers:
      - name: warden
        image: atomix-warden:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: RUST_BACKTRACE
            value: "1"
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 50053
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && warden --config /etc/atomix/config.json"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-warden-config

---
apiVersion: v1
kind: Service
metadata:
  name: atomix-warden
  namespace: atomix
spec:
  selector:
    app: atomix-warden
  # TODO: Expose warden ports
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atomix-warden-config
  namespace: atomix
data:
  config.json: |
    {
        "range_server": {
            "range_maintenance_duration": {
                "secs": 1,
                "nanos": 0
            },
            "proto_server_addr": "0.0.0.0:50054",
            "fast_network_addr": "0.0.0.0:50055",
            "fast_network_polling_core_id": 0,
            "background_runtime_core_ids": [0]
        },
        "universe": {
            "proto_server_addr": "atomix-universe:50056"
        },
        "frontend": {
            "proto_server_addr": "0.0.0.0:50057",
            "fast_network_addr": "0.0.0.0:50058",
            "fast_network_polling_core_id": 0,
            "background_runtime_core_ids": [0],
            "transaction_overall_timeout": {
                "secs": 10,
                "nanos": 0
            }
        },
        "epoch": {
            "proto_server_addr": "atomix-epoch:50050",
            "epoch_duration": {
                "secs": 0,
                "nanos": 1000000000
            }
        },
        "cassandra": {
            "cql_addr": "cassandra:9042"
        },
        "regions": {
            "test-region": {
                "warden_address": "0.0.0.0:50053",
                "epoch_publishers": [
                    {
                        "name": "ps1",
                        "zone": "test-region/a",
                        "publishers": [
                            {
                                "name": "ep1",
                                "backend_addr": "atomix-epoch-publisher:50051",
                                "fast_network_addr": "atomix-epoch-publisher:50052",
                                "fast_network_polling_core_id": 0
                            }
                        ]
                    }
                ]
            }
        }
    }
