name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code

    # TODO: Might need to wait a bit until Cassandra becomes ready.
    - name: Set up Docker Container
      run: docker run -d -p 9042:9042 --name cassandra cassandra:5.0

    - name: Install flatbuffers
      run: scripts/linux_install_flatbuffers.sh

    - name: Install protobuf
      run: sudo apt install -y protobuf-compiler

    - name: Install cqlsh
      run: pip install cqlsh

    - name: Build
      run: cargo build

    - name: Create keyspace
      run: |
        cqlsh -f schema/cassandra/atomix/keyspace.cql
        cqlsh -k atomix -f schema/cassandra/atomix/schema.cql

    - name: Run tests
      run: cargo test

  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: rangeserver
            tags: atomix-rangeserver:latest
          - target: warden
            tags: atomix-warden:latest
          - target: epoch_publisher
            tags: atomix-epoch-publisher:latest
          - target: epoch
            tags: atomix-epoch:latest
          - target: universe
            tags: atomix-universe:latest
          - target: frontend
            tags: atomix-frontend:latest

    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        target: ${{ matrix.target }}
        tags: ${{ matrix.tags }}
        push: false

  # TODO: Add an action to test deploying Atomix on a minikube cluster

  deploy-minikube:
    runs-on: ubuntu-latest
    needs: [build-docker-images]
    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code
      with:
        minikube-version: 'v1.33.1'
        driver: docker
        memory: 5120
        cpus: 2

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Build images in minikube
      run: |
        eval $(minikube docker-env)
        docker build -t atomix-rangeserver:latest --target rangeserver .
        docker build -t atomix-warden:latest --target warden .
        docker build -t atomix-epoch-publisher:latest --target epoch_publisher .
        docker build -t atomix-epoch:latest --target epoch .
        docker build -t atomix-universe:latest --target universe .
        docker build -t atomix-frontend:latest --target frontend .
    - name: Deploy and verify Atomix
      run: |
        cd kubernetes && ./deploy.sh

    - name: Clean up
      if: always()
      run: minikube delete
